name 'pan'
maintainer 'Jason Brody-Stewart-Stroeh'
maintainer_email 'info@jbbs-inc.com'
license 'Apache2'
description 'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version '0.0.1'
