source 'https://rubygems.org'

gem 'bundler', '1.10.5'

# cloud providers
gem 'chef'
gem 'kitchen-ec2'
#gem 'kitchen-google'
#gem 'kitchen-rackspace'
gem 'knife-ec2'
#gem 'knife-google'
#gem 'knife-rackspace'

# testing tools
gem 'berkshelf'
gem 'robocop'
gem 'chefspec'
gem 'test-kitchen'
gem 'foodcritic'


